steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/cicd-426910/cicd:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/cicd-426910/cicd:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yml
  - --image=gcr.io/cicd-426910/cicd:latest
  - --location=us-central1
  - --cluster=cicd-cluster
  options:
   logging: CLOUD_LOGGING_ONLY
